app1/urls.py
from django.urls import path
from app1.views import *
app_name='mawa'

urlpatterns=[
    path('anand/',anand,name='anand')
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='macha'

urlpatterns=[
    path('nani/',nani,name='nani')
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def anand(request):
    return render(request,'anand.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def nani(request):
    return render(request,'nani.html')

templates/anand.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SPECIFIC URL NAVIGATION IN JINJA TAGS</title>
</head>
<body>
    <center>
        <h1>this is anand html page</h1>
        <h2><a href="{% url 'macha:nani' %}"> go to nani page</a></h2>
    </center>
</body>
</html>

templates/nani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SPECIFIC URL NAVIGATION IN JINJA TAGS</title>
</head>
<body>
    <center>
        <h1>this is for nani view</h1>
        <h2><a href="{% url 'mawa:anand' %}">go to anand page</a></h2>
    </center>
</body>
</html>